[package]
name = "netpilot-transport-reality"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
netpilot-protocol-common = { path = "../../protocols/common" }
netpilot-transport-tls = { path = "../tls" }

[lints]
workspace = true
