[package]
name = "netpilot-protocol-vmess"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
netpilot-protocol-common = { path = "../common" }
sha2 = "0.10"
md-5 = "0.10"
aes-gcm = "0.10"
rand = "0.8"

[lints]
workspace = true
