[package]
name = "netpilot-config"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
netpilot-proxy = { path = "../proxy" }

[lints]
workspace = true
