[package]
name = "netpilot-tun"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
wintun-native = ["dep:netpilot-os-wintun"]

[dependencies]
netpilot-os-wintun = { path = "../os-wintun", optional = true }

[lints]
workspace = true
